#!/bin/bash
set -e

if ! command -v dialog > /dev/null; then
  echo "dialog is not installed, installing..." >&2
  sudo apt-get install dialog -y
fi

SELECTED=($( dialog --backtitle "Press 'space' to toggle an option, use arrow keys to go up/down, press enter to continue" --erase-on-exit --scrollbar --separate-output --checklist "Select Desktop Environment(s)" 10 35 5 \
  "1" "Arch" OFF \
  "2" "Fedora" OFF \
  "3" "Gentoo" OFF \
  "4" "Alpine" OFF \
  "5" "Artix" OFF \
  "6" "redcatOS" OFF \
  3>&1 1>&2 2>&3))

for i in "${SELECTED[@]}"; do
  case $i in
    1)
      distro+=("arch")
      packagemanager="pacman -Syu"
      extras="neofetch"
      ;;
    2)
      distro+=("fedora")
      packagemanager="dnf install"
      extras="neofetch"
      ;;
    3)
      distro+=("gentoo")
      packagemanager="emerge --ask --oneshot"
      extras="app-misc/neofetch"
      ;;
     4)
      distro+=("alpine")
      packagemanager="dnf install"
      extras="--repository https://dl-cdn.alpinelinux.org/alpine/3.16/community neofetch"
      ;;
     5)
      distro+=("artix")
      packagemanager="pacman -Syu"
      extras="neofetch"
      ;;
     6)
      echo "Coming soon! (This is already available on redcatOS if you have Dev Preview 2+)"
      ;;
  esac
done

clear

echo "Updating bedrock..."
sudo brl update

echo "Installing distro..."
sudo brl fetch ${distro[@]} && sudo ${packagemanager} ${extras}
echo "Done!"
